Выполнение задач по занятию 1
js-tasks-ru/jsbasic-20210906-2_tina-tezadova pull request #2
Opened 2021-09-10 07:31 UTC by TinaTezadova

2021-09-10 07:32 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-11 17:26 UTC, SinimaWath requested changes

2021-09-11 17:26 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  } else {return true;}
- Результать операции: `!name || name.length < 4 || name.indexOf(' ') > -1` - это boolean. Поэтому можно вернуть значение без if.
- indexOf - лучше заменить, на более понятный метод incudes

2021-09-11 17:26 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  } else {return false;}
Тут тоже можно без if, так как `newStr.includes('1xbet') || newStr.includes('xxx')` - возвращает boolean

2021-09-13 08:01 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-13 20:07 UTC, SinimaWath approved these changes
Все круто

2021-09-13 20:07 UTC, merged