Занятие 6: Классы и компоненты (1 Таблица с удаляемыми строками)
js-tasks-ru/jsbasic-20210906-2_tina-tezadova pull request #6
Opened 2021-10-01 13:13 UTC by TinaTezadova

Большая просьба подсказать как можно улучшить этот код. Все работает, но есть сомнения в правильности использованного подхода. Также очень смущает строка "target.parentNode.parentNode.remove();", но не нашла альтернативный способ поиска родителя родителя элемента.

2021-10-01 13:14 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-10-01 14:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-10-01 22:58 UTC, SinimaWath requested changes

2021-10-01 22:58 UTC, SinimaWath commented on 6-module/1-task/index.js
> +    this.#elem = new TableComponentTemplate(rows);
Давай не совмещать классы с функциональным стилем написания классов.

В современной разработки только **class** используется. Поэтому:
- Давай из функции TableComponentTemplate, сделаем функцию, которая просто возвращает готовую строку
- И уже в классе UserTable - будем создавать елемент

2021-10-01 22:58 UTC, SinimaWath commented on 6-module/1-task/index.js
> +      target.parentNode.parentNode.remove();
Давай через **closest** попробуем

2021-10-01 22:58 UTC, SinimaWath commented on 6-module/1-task/index.js
> +    btn.onclick = function(event) {
Обработчик события:
- Должен быть методом класса. Давай попробуем
- Он должен быть once

2021-10-01 22:58 UTC, SinimaWath commented on 6-module/2-task/index.js
> -}
Тут такие же советы как и к прошлому заданию

2021-10-04 14:24 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-10-05 13:46 UTC, SinimaWath requested changes

2021-10-05 13:46 UTC, SinimaWath commented on 6-module/2-task/index.js
> +  }
Давай для сделаем отдельный метод:
`onAddButtonClick` и используем его как обработчик события: `addButton.onclick = this.onAddButtonClick`

2021-10-05 13:46 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    };
Это должен быть метод, а не функцию в другой функции

2021-10-05 13:46 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    setTimeout(() => {
Зачем тут setTimeout? 

Высчитывай carouselSlide.offsetWidth - просто в момент клика

2021-10-05 14:27 UTC, TinaTezadova commented on 6-module/3-task/index.js
> +    setTimeout(() => {
Спасибо!

2021-10-05 16:01 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-10-06 20:13 UTC, SinimaWath requested changes

2021-10-06 20:13 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    this.#render = this.render();
А зачем тебе свойство #render ? У тебя уже есть метод с таким названием.

Кажется свойство должно называться: `#container`

2021-10-06 20:13 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    console.log(body.childNodes);
убери плиз console.log - и

2021-10-06 20:13 UTC, SinimaWath commented on 7-module/3-task/index.js
> +      this.onSliderClickEvent(value);
А зачем ты вызываешь этот метод только тут? Он же называется onSliderClickEvent. Поэтому в нем и должна быть вся логика:
```
slider.addEventListener('click', this.onSliderClickEvent)
```

2021-10-06 20:13 UTC, SinimaWath commented on 7-module/4-task/index.js
> +      document.addEventListener('pointermove', onMove);
Давай вынесем в метод:
`document.addEventListener('pointermove', onPointerMove);`

2021-10-06 20:13 UTC, SinimaWath commented on 7-module/4-task/index.js
> +      }, { once: true });
`document.addEventListener('pointerup', this.onPointerUp)`

2021-10-07 08:08 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-10-08 20:28 UTC, SinimaWath approved these changes
Все круто :) Давай дальше

2021-10-08 20:29 UTC, merged